<?php
/**
 * @file
 * dating_suite.strongarm.inc
 */

/**
 * Implementation of hook_strongarm().
 */
function dating_suite_strongarm() {
  $export = array();

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'additional_settings__active_tab_success_story';
  $strongarm->value = '';
  $export['additional_settings__active_tab_success_story'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_privatemsg_current_day';
  $strongarm->value = 'g:i a';
  $export['date_format_privatemsg_current_day'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_privatemsg_current_year';
  $strongarm->value = 'M j';
  $export['date_format_privatemsg_current_year'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_privatemsg_years';
  $strongarm->value = 'n/j/y';
  $export['date_format_privatemsg_years'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_options_success_story';
  $strongarm->value = array();
  $export['menu_options_success_story'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_parent_success_story';
  $strongarm->value = 'main-menu:0';
  $export['menu_parent_success_story'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_options_success_story';
  $strongarm->value = array(
    0 => 'status',
  );
  $export['node_options_success_story'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_preview_success_story';
  $strongarm->value = '1';
  $export['node_preview_success_story'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_submitted_success_story';
  $strongarm->value = 0;
  $export['node_submitted_success_story'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'page_title_type_success_story';
  $strongarm->value = '[current-page:page-title] | Success Story | [site:name] | [site:slogan]';
  $export['page_title_type_success_story'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'page_title_type_success_story_showfield';
  $strongarm->value = 0;
  $export['page_title_type_success_story_showfield'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'pathauto_node_success_story_pattern';
  $strongarm->value = 'success/[node:title]';
  $export['pathauto_node_success_story_pattern'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'save_continue_success_story';
  $strongarm->value = 'Save and add fields';
  $export['save_continue_success_story'] = $strongarm;

  return $export;
}
